name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - frontend

env:
  DOCKER_FRONTEND_TAG_LATEST: ${{ secrets.DOCKER_FRONTEND_TAG_LATEST }}
  DOCKER_FRONTEND_USERNAME: ${{ secrets.DOCKER_FRONTEND_USERNAME }}
  DOCKER_FRONTEND_PASSWORD: ${{ secrets.DOCKER_FRONTEND_PASSWORD }}
  ID_RSA: ${{ secrets.ID_RSA }}
  SERVER_USER: ${{ secrets.SERVER_USERNAME }}
  SERVER_IP: ${{ secrets.SERVER_IP }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        uses: actions/checkout@v4
      - run: cd apps/web && docker build -t $DOCKER_FRONTEND_TAG_LATEST .
      - run: docker login -u $DOCKER_FRONTEND_USERNAME -p $DOCKER_FRONTEND_PASSWORD
      - run: docker push $DOCKER_FRONTEND_TAG_LATEST
  deployment:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA }}
          known_hosts: "any"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: deploy
        uses: actions/checkout@v4
      - run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_FRONTEND_USERNAME -p $DOCKER_FRONTEND_PASSWORD"
      - run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $DOCKER_FRONTEND_TAG_LATEST"
      - run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker rm --force front || true"
      - run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd ~/hack/web && docker run --env-file .env -d -p 5173:5173 --name front $DOCKER_FRONTEND_TAG_LATEST"
      - run: rm -f ~/.ssh/id_rsa
      - run: echo "This job's status is ${{ job.status }}."
